FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
COPY model.py .
COPY utils.py .
COPY app.py .

RUN pip install --no-cache-dir -r requirements.txt

CMD bash -c "python model.py && python utils.py && uvicorn app:app --host 0.0.0.0 --port 7860"
